config/routes.rb
Chimailmadmin::Application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :emails
  resources :servers
  resources :domains


  root :to => 'emails#index'

end

app/models/alias.rb
class Alias < ActiveRecord::Base
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :emails
  has_and_belongs_to_many :servers
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :domain

  validates :address,
            :presence => true

  validates :domain_id,
            :presence => true


  def full_address
    "#{address}@#{domain.name}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/server.rb
class Server < ActiveRecord::Base
  validates :name,
            :uniqueness => true,
            :presence => true

  has_and_belongs_to_many :domains
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/domains_controller.rb
class DomainsController < InheritedResources::Base
end

app/controllers/emails_controller.rb
class EmailsController < InheritedResources::Base
  defaults :resource_class => Email, :collection_name => 'emails', :instance_name => 'email'

end

app/controllers/servers_controller.rb
class ServersController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/domains/_form.html.haml
.group
  = f.label :name, t("activerecord.attributes.domain.name", :default => "Name"), :class => :label
  = f.text_field :name, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :account_id, t("activerecord.attributes.domain.account_id", :default => "Account"), :class => :label
  = f.number_field :account_id, :class => 'number_field'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), domains_path, :class => "text_button_padding link_button"

app/views/domains/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/domains/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", domains_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_domain_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_domain_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Domain
    .inner
      = form_for @domain, :url => domain_path(@domain), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/domains/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", domains_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_domain_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Domains
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.domain.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @domains.each do |domain|
          %tr{:class => cycle("odd", "even")}
            %td
              = domain.id
            %td
              = link_to domain.name, domain_path(domain)
            %td
              = domain.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", domain_path(domain)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_domain_path(domain)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", domain_path(domain), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar')

app/views/domains/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", domains_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_domain_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Domain
    .inner
      = form_for :domain, :url => domains_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/domains/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", domains_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_domain_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", domain_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.domain.name", :default => t("activerecord.labels.name", :default => "Name"))
          \:
        = @domain.name
      %p
        %b
          = t("activerecord.attributes.domain.account_id", :default => t("activerecord.labels.account_id", :default => "Account"))
          \:
        = @domain.account_id
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_domain_path(@domain), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), domain_path(@domain), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ChiMailMadmin
    = stylesheet_link_tag :application 
    = javascript_include_tag :application
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} ChiMailMadmin
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              %a.logout{:href => "/logout"}= t("web-app-theme.logout", :default => "Logout")
        #main-navigation
          %ul.wat-cf
            %li= link_to "Emails", main_app.emails_path
            %li= link_to "Servers", main_app.servers_path
            %li= link_to "Domains", main_app.domains_path
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} ChiMailMadmin.
        #sidebar
          = yield :sidebar

app/views/servers/_form.html.haml
.group
  = f.label :server, t("activerecord.attributes.server.server", :default => "Server"), :class => :label
  = f.text_field :server, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :description, t("activerecord.attributes.server.description", :default => "Description"), :class => :label
  = f.text_field :description, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :server_type_id, t("activerecord.attributes.server.server_type_id", :default => "Server type"), :class => :label
  = f.number_field :server_type_id, :class => 'number_field'
  %span.description Ex: a simple text
.group
  = f.label :host_name, t("activerecord.attributes.server.host_name", :default => "Host name"), :class => :label
  = f.text_field :host_name, :class => 'text_field'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), servers_path, :class => "text_button_padding link_button"

app/views/servers/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/servers/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", servers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_server_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_server_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Server
    .inner
      = form_for @server, :url => server_path(@server), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/servers/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", servers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_server_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Servers
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.server.server", :default => t("activerecord.labels.server", :default => "Server"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @servers.each do |server|
          %tr{:class => cycle("odd", "even")}
            %td
              = server.id
            %td
              = link_to server.server, server_path(server)
            %td
              = server.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", server_path(server)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_server_path(server)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", server_path(server), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar')

app/views/servers/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", servers_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_server_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Server
    .inner
      = form_for :server, :url => servers_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/servers/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", servers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_server_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", server_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.server.server", :default => t("activerecord.labels.server", :default => "Server"))
          \:
        = @server.server
      %p
        %b
          = t("activerecord.attributes.server.description", :default => t("activerecord.labels.description", :default => "Description"))
          \:
        = @server.description
      %p
        %b
          = t("activerecord.attributes.server.server_type_id", :default => t("activerecord.labels.server_type_id", :default => "Server type"))
          \:
        = @server.server_type_id
      %p
        %b
          = t("activerecord.attributes.server.host_name", :default => t("activerecord.labels.host_name", :default => "Host name"))
          \:
        = @server.host_name
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_server_path(@server), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), server_path(@server), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')